#!/usr/python3

print("""░█▀▀█ ░█▀▀▀█ ░█▀▀▀█ ░█─▄▀ ▀█▀ ░█▀▀▀ 
░█─── ░█──░█ ░█──░█ ░█▀▄─ ░█─ ░█▀▀▀ 
░█▄▄█ ░█▄▄▄█ ░█▄▄▄█ ░█─░█ ▄█▄ ░█▄▄▄ 

░█▀▀█ ░█▀▀█ ─█▀▀█ ░█▀▀█ ░█▀▀█ ░█▀▀▀ ░█▀▀█ 
░█─▄▄ ░█▄▄▀ ░█▄▄█ ░█▀▀▄ ░█▀▀▄ ░█▀▀▀ ░█▄▄▀ 
░█▄▄█ ░█─░█ ░█─░█ ░█▄▄█ ░█▄▄█ ░█▄▄▄ ░█─░█ """);
print("[+]A FB Cookie Stealer Created By Prince Dev[+]")

import requests
import os
import time
import subprocess
import logging
import facebook
import random
import socket

class FacebookLogger:
    def __init__(self, target_link, target_id):
        self.target_link = target_link
        self.target_id = target_id
        self.logger = logging.getLogger('facebook_logger')
        self.logger.setLevel(logging.DEBUG)
        formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
        
        # Create a file handler
        file_handler = logging.FileHandler('facebook.log')
        file_handler.setLevel(logging.DEBUG)
        file_handler.setFormatter(formatter)
        self.logger.addHandler(file_handler)

    def log_message(self, message):
        self.logger.debug(message)

class FacebookAPI:
    def __init__(self, access_token):
        self.graph = facebook.GraphAPI(access_token)

    def get_user_info(self, user_id):
        return self.graph.get_object(user_id)

if __name__ == "__main__":
    fb_link = input("Enter the Facebook target link: ")
    fb_id = input("Enter the Facebook target ID: ")
    access_token = input("Enter the Facebook access token: ")

    fb_logger = FacebookLogger(fb_link, fb_id)
    fb_api = FacebookAPI(access_token)

    user_info = fb_api.get_user_info(fb_id)
    print("User Info:", user_info)

    fb_logger.log_message("Logged user info: {}".format(user_info))
